print ("--------------------")
print ("Tugas SISOP 1 Kelas B")
print ("--------------------")
print ("Nama : Zehan Azezair R")
print ("NPM : 21083010070")
print ("--------------------")
print ("Notes:enak turu")
print ("Halo Dunia")
print ("Ini adalah script bash pertamaku di Linux")
